merging branch homework3 to master
TaniaVoitsekhovska/MySQL-Homework pull request #4
Opened 2020-02-20 10:49 UTC by TaniaVoitsekhovska

2020-02-23 16:55 UTC, vtymtsiv requested changes
Some statements can't be executed.

2020-02-23 16:55 UTC, VolodymyrTymtsiv commented on hw2.sql
> +SELECT id, MAX(number_of_pages) as Max_number_of_pages FROM book;
This statement can't be executed, you can't show id with the result of `max()`.

> Error Code: 1140. In aggregated query without GROUP BY, expression 1 of SELECT list contains nonaggregated column 'library.book.id'; this is incompatible with sql_mode=only_full_group_by

2020-02-23 16:55 UTC, VolodymyrTymtsiv commented on hw2.sql
> +SELECT id, category, SUM(book_price) as total_cost_of_books FROM book WHERE category = 'Художня проза';
Same here

2020-02-23 16:55 UTC, VolodymyrTymtsiv commented on hw2.sql
> +SELECT id, MIN(book_price) as lowest_book_price FROM book;
Same

2020-02-23 16:57 UTC, VolodymyrTymtsiv commented on hw2.sql
> +SET sql_safe_updates = 1;
It is not necessary to run all these statements with sql_safe_updates = 0

2020-02-24 15:34 UTC, TaniaVoitsekhovska commented on hw2.sql
> +SELECT id, MAX(number_of_pages) as Max_number_of_pages FROM book;
fixed

2020-02-24 15:34 UTC, TaniaVoitsekhovska commented on hw2.sql
> +SELECT id, category, SUM(book_price) as total_cost_of_books FROM book WHERE category = 'Художня проза';
fixed

2020-02-24 15:35 UTC, TaniaVoitsekhovska commented on hw2.sql
> +SELECT id, MIN(book_price) as lowest_book_price FROM book;
fixed

2020-02-24 15:35 UTC, TaniaVoitsekhovska commented on hw2.sql
> +SET sql_safe_updates = 1;
fixed

2020-02-24 21:20 UTC, vtymtsiv approved these changes

2020-02-25 08:32 UTC, merged